import asyncio
import json
import sys
import threading
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

from fastapi import FastAPI, File, HTTPException, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from env.env import ContentModerationEnv
from env.models import ModerationAction
from server.discord_bot import discord_service
from server import discord_live_hub as live_hub
from server import ocr_service
from server.meme_classifier import classify_meme_text

app = FastAPI(title="Content Moderation OpenEnv")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── RL environment (OpenEnv task runner) ──────────────────────────────────────
_lock = threading.Lock()
env   = ContentModerationEnv()


@app.get("/")
def root():
    return {"status": "ok"}


@app.get("/health")
def health():
    return {"status": "ok"}


_METRICS_PATH = Path(__file__).resolve().parent.parent / "results" / "rl_training_metrics.json"


@app.get("/training/metrics")
def training_metrics():
    """Before/after RL evaluation metrics for the Training dashboard.

    Generated by ``RLtrainer.ipynb`` or ``python scripts/rl_trainer.py …``.
    """
    if not _METRICS_PATH.exists():
        return {
            "loaded": False,
            "message": "No metrics file yet. Run: python scripts/rl_trainer.py eval-comparison --best-of 4",
            "path": str(_METRICS_PATH),
        }
    try:
        data = json.loads(_METRICS_PATH.read_text(encoding="utf-8"))
        data["loaded"] = True
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.api_route("/reset", methods=["GET", "POST"])
def reset(task_id: str = "task1"):
    with _lock:
        try:
            obs = env.reset(task_id)
            return obs.model_dump()
        except Exception as e:
            raise HTTPException(status_code=422, detail=str(e))


@app.post("/step")
def step(action: ModerationAction):
    with _lock:
        try:
            obs, reward, done, info = env.step(action)
            return {
                "observation": obs.model_dump(),
                "reward":      reward.model_dump(),
                "done":        done,
                "info":        info,
            }
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))


@app.get("/state")
def state():
    with _lock:
        try:
            return env.state()
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))


@app.get("/posts")
def get_posts(limit: int = 20, difficulty: Optional[str] = None):
    """Return posts from the OpenEnv dataset, optionally filtered by difficulty."""
    try:
        data_path = Path(__file__).parent.parent / "data" / "posts.json"
        posts = json.loads(data_path.read_text(encoding="utf-8"))
        if difficulty:
            posts = [p for p in posts if p.get("difficulty") == difficulty]
        return {"posts": posts[:limit], "total": len(posts)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/stats")
def get_stats():
    """Aggregate stats across all OpenEnv posts — used by the frontend dashboard."""
    try:
        data_path = Path(__file__).parent.parent / "data" / "posts.json"
        posts = json.loads(data_path.read_text(encoding="utf-8"))
        decisions = [p["gold_label"]["decision"] for p in posts]
        difficulties = [p.get("difficulty", "unknown") for p in posts]
        return {
            "total":     len(posts),
            "approved":  decisions.count("approve"),
            "removed":   decisions.count("remove"),
            "escalated": decisions.count("escalate"),
            "by_difficulty": {
                d: difficulties.count(d) for d in set(difficulties)
            },
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── AI Moderator (user-facing) ────────────────────────────────────────────────

class ModerateRequest(BaseModel):
    content:  str            = Field(..., min_length=1, max_length=2000)
    platform: Optional[str] = "social_media"


class FeedbackRequest(BaseModel):
    post_id:     str
    content:     str
    decision:    str
    reason_code: str
    severity:    str
    confidence:  float
    explanation: str
    model:       str
    rating:      int           = Field(..., ge=1, le=10)
    comment:     Optional[str] = None


_feedback_store: list[dict] = []


@app.post("/moderate")
def moderate_content(req: ModerateRequest):
    """Have OpenAI moderate user-submitted content and return a full decision."""
    from env.moderator import moderate
    try:
        return moderate(req.content, req.platform or "social_media")
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"AI moderator unavailable: {e}")


@app.post("/feedback")
def submit_feedback(req: FeedbackRequest):
    """Store the user's 1–10 rating of the AI's moderation call."""
    _feedback_store.append(req.model_dump())
    return {"stored": True, "total": len(_feedback_store)}


@app.get("/history")
def get_history():
    """Return all past moderation decisions with user ratings, newest first."""
    return list(reversed(_feedback_store))


class DiscordActionRequest(BaseModel):
    action: str = Field(..., description="accept | delete | escalate | flag")


def _prewarm_rl_classifier():
    """Eagerly load the local Qwen / RL model in a background thread so the
    first Discord message doesn't pay the model-load cost (and so we surface
    load failures in the server log immediately).
    """
    import os
    if str(os.getenv("USE_LOCAL_LLM", "false")).strip().lower() not in ("true", "1", "yes", "y"):
        return
    if os.getenv("DISCORD_CLASSIFIER", "").strip().lower() not in ("rl", "auto"):
        return

    def _load():
        try:
            print("[startup] pre-warming RL core (importing inference)…")
            import inference  # noqa: F401  (imports trigger model load)
            print("[startup] RL core ready (model =", getattr(inference, "HF_MODEL_ID", "?"), ")")
        except Exception as exc:
            print(f"[startup] RL core failed to load: {exc}. "
                  f"Discord classifier will fall back to moderator/heuristic.")

    threading.Thread(target=_load, name="prewarm-rl", daemon=True).start()


def _prewarm_ocr():
    """Pre-load EasyOCR in a background thread so the first /ocr/moderate is fast."""
    threading.Thread(target=ocr_service.warm, name="prewarm-ocr", daemon=True).start()


@app.on_event("startup")
async def startup_discord_and_live_hub():
    live_hub.set_main_loop(asyncio.get_running_loop())
    discord_service.start()
    _prewarm_rl_classifier()
    _prewarm_ocr()


@app.websocket("/ws/discord/live")
async def discord_live_websocket(websocket: WebSocket):
    await websocket.accept()
    await live_hub.register(websocket)
    try:
        await websocket.send_json(
            {"type": "hello", "discord": discord_service.status()}
        )
        # Replay recent in-memory records so the UI is not empty after refresh.
        records = discord_service.get_records(pending_only=False)
        records = sorted(records, key=lambda r: r.get("created_at", ""))[-100:]
        for rec in records:
            await websocket.send_json(
                {"type": "discord_moderation", "record": rec, "replay": True}
            )
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        pass
    finally:
        await live_hub.unregister(websocket)


@app.get("/discord/status")
def discord_status():
    return discord_service.status()


@app.get("/discord/reviews")
def discord_reviews(pending_only: bool = False):
    return {"items": discord_service.get_records(pending_only=pending_only)}


_ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/jpg", "image/png", "image/webp"}
_MAX_IMAGE_BYTES = 8 * 1024 * 1024  # 8 MB upload cap


@app.get("/ocr/status")
def ocr_status():
    return ocr_service.status()


@app.post("/ocr/moderate")
async def ocr_moderate(image: UploadFile = File(...)):
    """OCR an uploaded meme/image, then run the extracted text through the
    same moderation core that handles Discord messages. Returns the OCR text,
    the moderation decision, severity, and a fine-grained tag.
    """
    ctype = (image.content_type or "").lower().split(";")[0].strip()
    if ctype not in _ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=415,
            detail=f"Unsupported content-type: {image.content_type!r}. Use JPEG, PNG, or WebP.",
        )

    data = await image.read()
    if not data:
        raise HTTPException(status_code=400, detail="Empty file upload")
    if len(data) > _MAX_IMAGE_BYTES:
        raise HTTPException(status_code=413, detail="Image too large; keep it under 8 MB.")

    text, engine = ocr_service.extract_text(data)
    moderation = classify_meme_text(text)
    return {
        "ocr_engine": engine,
        "extracted_text": text,
        "image_bytes": len(data),
        "filename": image.filename,
        "moderation": moderation,
    }


@app.post("/discord/review/{message_id}")
def discord_review_action(message_id: int, req: DiscordActionRequest):
    try:
        record = discord_service.apply_action(message_id=message_id, action=req.action)
        return {"ok": True, "record": record}
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"discord action failed: {exc}")


def main():
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860)


if __name__ == "__main__":
    main()
